#!/bin/bash
# declare STRING variable

#....
# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
# ...

STRING="Welcome To Aircel PocketInternet"
#print variable on a screen
echo $STRING

MY_DIR=`dirname $0`

FILE="$MY_DIR/license.txt"

if [ -f $FILE ];
then
   echo "File $FILE exists."
else
   echo "File $FILE does not exist."
   exit
fi

echo "*** File - $FILE contents ***"
cat $FILE

while true
do
  echo -n " Do you agree to these terms? (yes/no): "
  read CONFIRM
  case $CONFIRM in
    yes|YES) break ;;
    no|NO)
      echo "
	User declined the license agreement.		
"
      exit
      ;;
    *) echo "
	That is not vaild input.	
"
  esac
done

if [ -d "/opt/Aircel" ]; then
    echo "Aircel folder already exist"
    exit
else
    #echo "DIRECTORY not exists"
    sudo mkdir /opt/Aircel  
fi

sudo modprobe usbserial vendor=0x22f4 product=0x0026

#Copy files
sudo cp $MY_DIR/style /opt/Aircel

